### ISSUE TITLE
Not good manners

### ISSUE THREAD

**Issue by tarlepp** [gyanl/MAITProgrammersGuild#8]
Seems like this whole repo is just for the T-Shirt, actually this isn't a real project (just created empty one) and then added "issues" that doesn't exists yet.

ping @digitalocean

**Comment by obeid** [comment]
👍  @digitalocean

**Comment by ryanpq** [comment]
Thanks for reaching out.  

@gyanl - You can earn your shirt through PRs to your own repository, there is nothing wrong with that though we would prefer that you make a meaningful contribution to open source.  There is NO REQUIREMENT to tag issues Hacktoberfest for them to count.  All PRs to public GitHub projects count.  By tagging issues that do not specify actual issues you are just wasting other's time.  Please remove the tags from your issues so that others can focus on projects asking for real contributions.  Your PRs here will still count toward your shirt.

**Comment by grant-park** [comment]
well this is pretty sad....ill move onto a diff repo, sigh

**Comment by gyanl** [comment]
Hey @tarlepp, @obeid, @ryanpq, @sungjp : I have a college programming club, and I've been trying to get them to start using Github and contributing to open source projects - I figured people might get into it if they get the Hacktoberfest t-shirt, so I'm using that as bait to get them to at least learn how to use Github and send PRs. 

I didn't realise tagging the issues with Hacktoberfest would get this much visibility, but there will be a legitimate project here over the next few days, and I'll remove the Hacktoberfest tags and make the repo private till then. Thanks!
